name: Bygg branch

on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - .github/common_workflows/**

jobs:
  build-branch:
    runs-on: ubuntu-latest
    steps:

      - name: Sjekk ut koden
        uses: actions/checkout@v2

      - name: Kompiler
        uses: navikt/pb-common-gh-actions/build@v0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}